version: '3'
services:
  selenoid:
    container_name: "selenoid"
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "${PWD}:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/video:/opt/selenoid/video"
      - "${PWD}/logs:/opt/selenoid/logs"
      - "${PWD_FILES}:/opt/selenoid/files:ro"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    container_name: "selenoid-ui"
    image: aerokube/selenoid-ui:latest
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  jenkins:
    container_name: "jenkins"
    image: jenkins/jenkins:lts
    volumes:
      - "${jenkins_home}:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${jenkins_home}/downloads:/var/jenkins_home/downloads"
    ports:
      - "8080:8080"
      - "50000:50000"